-- Auto-generated catalog sync (titles + images + SEO text)
-- Source image CSV: c:/Users/yuvak/Downloads/all_cloudinary_images.csv
-- Generated at: 2026-02-17T15:26:49.772Z

BEGIN;

CREATE TEMP TABLE desired_catalog (
  product_id TEXT PRIMARY KEY,
  title_en TEXT NOT NULL,
  image_url TEXT NOT NULL,
  description_en TEXT NOT NULL,
  specifications_en TEXT NOT NULL,
  usage_en TEXT NOT NULL,
  unit_value NUMERIC,
  unit_type TEXT,
  insert_mrp NUMERIC NOT NULL,
  insert_price NUMERIC NOT NULL,
  shipping_charges NUMERIC NOT NULL,
  stock_quantity INTEGER NOT NULL,
  category_key TEXT NOT NULL
);

INSERT INTO desired_catalog (
  product_id, title_en, image_url, description_en, specifications_en, usage_en,
  unit_value, unit_type, insert_mrp, insert_price, shipping_charges, stock_quantity, category_key
)
VALUES
  ('BC001', 'Marula Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330379/marulaoel-kaltgepresst-heess-247x296_btdods.webp', 'Marula Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '10 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 10, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC002', 'Olive Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330380/oliveoil_1200x1200_tkz0x9.webp', 'Olive Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC006', 'Sweet Almond Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330378/Sweet_Almond_Oill-500x500-1-247x296_phqgmu.webp', 'Sweet Almond Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '100 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 100, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC005', 'Jojoba Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330378/Jojoba_Oil_j6vhih.webp', 'Jojoba Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC089', 'Avocado Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330378/Avocado_Oil_wdnceb.webp', 'Avocado Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC032', 'Coconut Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330371/Coconut_Oil_lnj84f.webp', 'Coconut Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC033', 'Castor Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330371/Castor_Oil_saoxa7.webp', 'Castor Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC034', 'Black Sesame Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330371/Black_Sesame_Oil_tpiuis.avif', 'Black Sesame Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC012', 'Grapeseed Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330370/Grapeseed_Oil_uzou5w.webp', 'Grapeseed Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '50 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 50, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC023', 'Calendula Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330370/Calendula-Oil-247x296_jmejmk.webp', 'Calendula Oil is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '20 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 20, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC030', 'Steam Distilled Rose Water', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330371/Steam_Distilled_rose_water_uxipwo.webp', 'Steam Distilled Rose Water is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '100 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 100, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC024', 'Witch Hazel', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330370/witchhazel-247x296_w8y0p4.webp', 'Witch Hazel is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '20 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 20, 'ml', 188, 150, 70, 100, 'oil_liquid'),
  ('BC036', 'De-Mineralized Water', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330370/De-Mineralized_Water_narng3.png', 'De-Mineralized Water is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '1 l | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 1, 'l', 188, 150, 70, 100, 'oil_liquid'),
  ('BC090', 'Red Wine', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330367/Red_Wine_jvsgoj.webp', 'Red Wine is a high-quality ingredient for skincare, haircare, and personal care formulations. It blends well in daily use products and DIY recipes.', '100 ml | Premium cosmetic ingredient', 'Use directly or blend with other ingredients as required. For topical use, apply a small amount and adjust as needed.', 100, 'ml', 125, 100, 70, 100, 'oil_liquid'),
  ('BC025', 'Soap Base (Melt & Pour)', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330367/Soap_Base_Melt_Pour_tz3ggv.webp', 'Soap Base (Melt & Pour) is a ready-to-use base designed for simple and consistent product making. Ideal for customized soaps and cleansers.', '1 kg | Ready-to-use base', 'Measure required quantity, add fragrance/color/actives as needed, mix thoroughly, and use in final formulation.', 1, 'kg', 75, 60, 70, 100, 'base'),
  ('BC035', 'Pearly Shampoo Base', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330366/Pearly_Shampoo_Base_svhqxv.webp', 'Pearly Shampoo Base is a ready-to-use base designed for simple and consistent product making. Ideal for customized soaps and cleansers.', '1 kg | Ready-to-use base', 'Measure required quantity, add fragrance/color/actives as needed, mix thoroughly, and use in final formulation.', 1, 'kg', 75, 60, 70, 100, 'base'),
  ('BC013', 'Coco Glucoside', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330366/Coco_Glucoside_x5jwv5.webp', 'Coco Glucoside is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '100 gm | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 100, 'gm', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC021', 'Coco Betaine', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330366/Coco_Betaine_k1kxwv.webp', 'Coco Betaine is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '100 ml | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 100, 'ml', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC029', 'Decyl Glucoside', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330366/Decyl_Glucoside_waaq8n.webp', 'Decyl Glucoside is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '100 gm | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 100, 'gm', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC003', 'Iscaguard PEG', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330365/Iscaguard_PEG_n5x94y.webp', 'Iscaguard PEG is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '50 ml | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 50, 'ml', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC031', 'Vegetable Glycerin', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330364/Vegetable_Glycerin_vhzkyd.webp', 'Vegetable Glycerin is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '100 ml | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 100, 'ml', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC017', 'Aloe Vera Gel', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330363/Aloe_Vera_Gel_uikihn.webp', 'Aloe Vera Gel is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '100 gm | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 100, 'gm', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC091', 'Aloe Vera Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330365/Aloe_Vera_Powder_c4aazs.webp', 'Aloe Vera Powder is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '50 gm | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 50, 'gm', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC052', 'Vitamin E Capsules', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330363/Vitamin_E_Capsules_g7lo3w.jpg', 'Vitamin E Capsules is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '10 pcs | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 10, 'pcs', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC051', 'Honey', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330362/Honey_wyatjj.webp', 'Honey is a reliable formulation ingredient used to improve cleansing, texture, moisture balance, or stability in personal care products.', '100 gm | Formulation ingredient', 'Use in formulation phase as required. Start with small percentages and adjust based on product performance.', 100, 'gm', 75, 60, 70, 100, 'surfactant_additive'),
  ('BC007', 'Cocoa Butter', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330362/Cocoa_Butter_j7zgzo.webp', 'Cocoa Butter is commonly used to improve richness, structure, and skin feel in creams, balms, and solid formulations.', '50 gm | Rich texture and structure aid', 'Melt or disperse as required in formulation. Blend uniformly for smooth texture and stable finish.', 50, 'gm', 75, 60, 70, 100, 'butter_wax_binder'),
  ('BC008', 'Avocado Butter', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330362/Avocado_Butter_mtl8nj.webp', 'Avocado Butter is commonly used to improve richness, structure, and skin feel in creams, balms, and solid formulations.', '50 gm | Rich texture and structure aid', 'Melt or disperse as required in formulation. Blend uniformly for smooth texture and stable finish.', 50, 'gm', 75, 60, 70, 100, 'butter_wax_binder'),
  ('BC022', 'Beeswax', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330361/Beeswax_me4tva.webp', 'Beeswax is commonly used to improve richness, structure, and skin feel in creams, balms, and solid formulations.', '50 gm | Rich texture and structure aid', 'Melt or disperse as required in formulation. Blend uniformly for smooth texture and stable finish.', 50, 'gm', 75, 60, 70, 100, 'butter_wax_binder'),
  ('BC010', 'Emulsifying Wax (E-Wax)', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330361/Emulsifying_Wax_E-Wax_zadp1u.jpg', 'Emulsifying Wax (E-Wax) is commonly used to improve richness, structure, and skin feel in creams, balms, and solid formulations.', '50 gm | Rich texture and structure aid', 'Melt or disperse as required in formulation. Blend uniformly for smooth texture and stable finish.', 50, 'gm', 75, 60, 70, 100, 'butter_wax_binder'),
  ('BC077', 'Gond Katira', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330360/Gond_Katira_grhwtr.jpg', 'Gond Katira is commonly used to improve richness, structure, and skin feel in creams, balms, and solid formulations.', '50 gm | Rich texture and structure aid', 'Melt or disperse as required in formulation. Blend uniformly for smooth texture and stable finish.', 50, 'gm', 75, 60, 70, 100, 'butter_wax_binder'),
  ('BC020', 'Corn Starch', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330359/Corn_Starch_oyyrzt.jpg', 'Corn Starch is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC026', 'Arrowroot Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330358/Arrowroot_Powder_vt394q.webp', 'Arrowroot Powder is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC027', 'Potato Starch', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330358/Potato_Starch_hl6zmv.jpg', 'Potato Starch is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC028', 'Rice Starch', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330358/Rice_Starch_c05vov.jpg', 'Rice Starch is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC092', 'Rice Flour', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330358/Rice_Flour_wgqczq.jpg', 'Rice Flour is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 59, 40, 70, 100, 'clay_starch_flour'),
  ('BC047', 'Multani Mitti', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330357/Multani_Mitti_xlkqhu.webp', 'Multani Mitti is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC048', 'Kaolin Clay', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330357/Kaolin_Clay_ldjyo0.webp', 'Kaolin Clay is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC049', 'Rose Clay', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330357/Rose_Clay_w1u91p.webp', 'Rose Clay is used in powders, packs, and cleansing blends to improve texture, absorb excess oil, and support a smooth finish.', '50 gm | Fine-grade powder', 'Mix with water, rose water, aloe gel, or other base ingredients to prepare face packs, masks, or powder blends.', 50, 'gm', 75, 60, 70, 100, 'clay_starch_flour'),
  ('BC050', 'Coffee Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330356/Coffee_Powder_xkott9.jpg', 'Coffee Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC054', 'Cinnamon Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330356/Cinnamon_Powder_gpzvdf.jpg', 'Cinnamon Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('HP001', 'Banana Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330355/Banana_Powder_gy53jh.jpg', 'Banana Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC055', 'Manjistha Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330354/Manjistha_Powder_ae1an3.webp', 'Manjistha Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC056', 'Licorice Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330354/Licorice_Powder_wfayvn.webp', 'Licorice Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC057', 'Sandalwood Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330354/Sandalwood_Powder_i5zykt.jpg', 'Sandalwood Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC073', 'Arjuna Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330353/Arjuna_Powder_my7y4z.webp', 'Arjuna Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC059', 'Kasthuri Pasupu', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330353/Kasthuri_Pasupu_ylo2cp.jpg', 'Kasthuri Pasupu is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC060', 'Tulasi Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330353/Tulasi_Powder_wsc5ni.jpg', 'Tulasi Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('HP003', 'Neem Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330350/Neem_Powder_v4tan0.jpg', 'Neem Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC045', 'Neem Leaves Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330352/Neem_Leaves_Powder_v5kit9.webp', 'Neem Leaves Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC074', 'Kuppintaaku Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330350/Kuppintaaku_Powder_e0o0cx.jpg', 'Kuppintaaku Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC075', 'Pomegranate Seeds Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330350/Pomegranate_Seeds_Powder_w9yjc7.jpg', 'Pomegranate Seeds Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC058', 'Red Sandal Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330350/Red_Sandal_Powder_rwi78s.jpg', 'Red Sandal Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC061', 'Beetroot Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330350/Beetroot_Powder_txfoqc.webp', 'Beetroot Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC093', 'Rose Petal Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330349/Rose_Petal_Powder_izkjus.webp', 'Rose Petal Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('HP002', 'Orange Peel Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330349/Orange_Peel_Powder_we45ce.webp', 'Orange Peel Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC063', 'Lemon Peel Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330347/Lemon_Peel_Powder_mwnb6x.webp', 'Lemon Peel Powder is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC076', 'Red Toor Dal', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330347/Red_Toor_Dal_wq44kw.jpg', 'Red Toor Dal is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '50 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 50, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC083', 'Sambar Onions', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330347/Sambar_Onions_lcvvl1.jpg', 'Sambar Onions is a versatile herbal ingredient for skin packs, soaps, and natural care formulations. Helps improve overall formulation quality.', '100 gm | Herbal powder', 'Mix with suitable liquid to make a paste or add to soap/pack formulations. Use regularly for best results.', 100, 'gm', 75, 60, 70, 100, 'herbal_skin_soap'),
  ('BC039', 'Hibiscus Flower Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330347/Hibiscus_Flower_Powder_ztwvuq.jpg', 'Hibiscus Flower Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC094', 'Hibiscus Leaves Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330346/Hibiscus_Leaves_Powder_hxbnfl.jpg', 'Hibiscus Leaves Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC037', 'Henna Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330346/Henna_Powder_ld7hd8.jpg', 'Henna Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC095', 'Curry Leaves Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330346/Curry_Leaves_Powder_vixrqz.jpg', 'Curry Leaves Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC096', 'Avarampoo Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330346/Avarampoo_Powder_jraflc.jpg', 'Avarampoo Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC038', 'Amla Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330344/Amla_Powder_vmrnvw.jpg', 'Amla Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC097', 'Kalonji Seeds', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330344/Kalonji_Seeds_ptbhoh.jpg', 'Kalonji Seeds is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC019', 'Bhringraj Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330343/Bhringraj_Powder_qtr6sw.jpg', 'Bhringraj Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC078', 'Rosemary Leaves', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330343/Rosemary_Leaves_ytsay3.jpg', 'Rosemary Leaves is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC079', 'Vetiver (Vattiveru) Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330343/Vetiver_Vattiveru_Powder_ua3ky0.jpg', 'Vetiver (Vattiveru) Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC080', 'Jatamansi Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330343/Jatamansi_Powder_e71rv7.jpg', 'Jatamansi Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC042', 'Brahmi Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330342/Brahmi_Powder_twhuf0.jpg', 'Brahmi Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC043', 'Fenugreek Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330342/Fenugreek_Powder_mhuru0.jpg', 'Fenugreek Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC081', 'Gaddi Chamanthi Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330340/Gaddi_Chamanthi_Powder_xuwxft.jpg', 'Gaddi Chamanthi Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC082', 'Tangedu Aakula Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330340/Tangedu_Aakula_Powder_ahkwoo.jpg', 'Tangedu Aakula Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC046', 'Custard Apple Seeds Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330339/Custard_Apple_Seeds_Powder_s66fsk.jpg', 'Custard Apple Seeds Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC041', 'Reetha (Soapnut) Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330339/Reetha_Soapnut_Powder_wbijkc.jpg', 'Reetha (Soapnut) Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC040', 'Shikakai Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330339/Shikakai_Powder_oednji.jpg', 'Shikakai Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC084', 'Flax Seeds Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330339/Flax_Seeds_Powder_sqrx4i.jpg', 'Flax Seeds Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC085', 'Maredu Gujju Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330339/Maredu_Gujju_Powder_zqnwdr.jpg', 'Maredu Gujju Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC044', 'Triphala Powder', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330338/Triphala_Powder_hn9hlh.jpg', 'Triphala Powder is a traditional herbal ingredient used in hair masks, herbal cleansers, and scalp care formulations.', '50 gm | Herbal powder', 'Blend with water, curd, aloe gel, or oils to prepare hair packs and herbal treatments. Apply and rinse after use.', 50, 'gm', 75, 60, 70, 100, 'herbal_hair'),
  ('BC064', 'Lavender Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330338/Lavender_Essential_Oil_o2wsgy.jpg', 'Lavender Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('EO001', 'Rose Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330337/Rose_Essential_Oil_wfvqhp.jpg', 'Rose Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('EO002', 'Jasmine Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330338/Jasmine_Essential_Oil_hnlntp.jpg', 'Jasmine Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('EO004', 'Ylang Ylang Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330337/Ylang_Ylang_Essential_Oil_o68e8t.jpg', 'Ylang Ylang Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('EO003', 'Tea Tree Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330339/Tea_Tree_Essential_Oil_nalemt.webp', 'Tea Tree Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('EO005', 'Cedarwood Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330338/Cedarwood_Essential_Oil_fjcokp.webp', 'Cedarwood Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('BC070', 'Wintergreen Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330338/Wintergreen_Essential_Oil_gts5ic.webp', 'Wintergreen Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('BC071', 'Lemon Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330338/Lemon_Essential_Oil_sgcebz.webp', 'Lemon Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil'),
  ('BC072', 'Peppermint Essential Oil', 'https://res.cloudinary.com/dur6fkyoz/image/upload/w_1000,h_1000,c_fill,g_auto,q_auto,f_auto/v1771330337/Peppermint_Essential_Oil_wh1fby.jpg', 'Peppermint Essential Oil is a concentrated aromatic essential oil used in soaps, skincare blends, and fragrance formulations.', '15 ml | Concentrated aromatic oil', 'Use 1-2 drops in blends, soaps, creams, or diffusers. Always dilute before direct skin application.', 15, 'ml', 269, 200, 70, 100, 'essential_oil')
;

-- 1) Update existing products to exact target title/image/content
UPDATE public.products p
SET
  title_en = d.title_en,
  image_url = d.image_url,
  description_en = d.description_en,
  specifications_en = d.specifications_en,
  usage_en = d.usage_en,
  unit_value = d.unit_value,
  unit_type = d.unit_type,
  shipping_charges = COALESCE(p.shipping_charges, d.shipping_charges),
  is_active = TRUE,
  updated_at = NOW()
FROM desired_catalog d
WHERE p.product_id = d.product_id;

-- 2) Insert missing products from target catalog
INSERT INTO public.products (
  product_id, title_en, description_en, specifications_en, usage_en,
  image_url, mrp, current_price, shipping_charges, stock_quantity,
  is_active, is_best_seller, is_new, unit_value, unit_type
)
SELECT
  d.product_id, d.title_en, d.description_en, d.specifications_en, d.usage_en,
  d.image_url, d.insert_mrp, d.insert_price, d.shipping_charges, d.stock_quantity,
  TRUE, FALSE, TRUE, d.unit_value, d.unit_type
FROM desired_catalog d
LEFT JOIN public.products p ON p.product_id = d.product_id
WHERE p.id IS NULL;

-- 3) Deactivate non-catalog / duplicate products to prevent UI mismatch
UPDATE public.products
SET is_active = FALSE, updated_at = NOW()
WHERE product_id IN ('810', '811', 'BC004', 'BC009', 'BC011', 'BC014', 'BC015', 'BC016', 'BC018');

-- 4) Safety check: no duplicate active titles in this catalog
-- SELECT title_en, COUNT(*) FROM public.products WHERE is_active = TRUE GROUP BY title_en HAVING COUNT(*) > 1;

COMMIT;
