import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
    // Basic redirect to sitemap.xml generated by Next.js app/sitemap.ts
    const sitemapUrl = new URL('/sitemap.xml', req.url);
    return NextResponse.redirect(sitemapUrl);
}
